name: release

on:
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Yarn v1 cache
        id: yarn-cache-dir
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: cache
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
          path: |
            dist
            **/node_modules
            ${{ steps.yarn-cache-dir.outputs.dir }}

      - name: Setup git
        run: |
          git config user.name "mynd.co[bot]"
          git config user.email "opensource@mynd.co"
          git config --global init.defaultBranch master

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable --immutable-cache

      - name: Build affected projects
        shell: bash
        run: yarn nx affected --base=last-release --target=build

      - name: Version affected projects
        shell: bash
        run: yarn nx affected --base=last-release --target=version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag last-release
        shell: bash
        run: git tag -f last-release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
